- name: Install dispatch
  hosts : dispatch
  become: yes
  tasks:
  - name: install golang 
    ansible.builtin.yum:
      name: golang 
      state: installed

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out #output is variable name
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    become: yes # we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: print the directory stats
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - when: directory.stat.exists == False
    name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download dispatch and extract
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /app
      remote_src: yes

  - name: Download the dependencies and build the software
    ansible.builtin.shell: "{{item}}"
    args:
      chdir: /app
    with_items:
      - go mod init dispatch
      - go get
      - go build

  - name: copy dispatch service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: deamon reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: restart dispatch
    ansible.builtin.service:
      name: dispatch
      state: restarted
      enabled: true